pipeline {
  agent any

stages {
  stage ('kubectl'){
    steps {
      kubeconfig(credentialsId: 'egebezirci', caCertificate: '', serverUrl: 'https://127.0.0.1:40763') {
        sh "helm upgrade --install frontend  -n www --create-namespace  ./charts/www"
      }

    }
  }
}
}
